server:
  port: 8088

spring:
  application:
    name: brand-service
  datasource:
    url: jdbc:mysql://localhost:3306/heima
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  type-aliases-package: com.fjx.test.pojo
